### ISSUE TITLE
IDL dependency and source code naming.

### ISSUE THREAD

**Issue by peijin94** [kuznetsov-radio/GRFF#2]
If the `idl_export.h` is not heavily required, we should remove it in the Messager.h to embrace the broader user without IDL installed.

`IDLinterface.cpp` is the overall entry to the program, with the OMP paralization and major loop inside.
could be renamed to `interface.cpp`.

It's confusing that `IDLinterface.cpp` is called by `Pythoninterface.cpp`.

**Comment by kuznetsov-radio** [comment]
Corrected

**Comment by kuznetsov-radio** [comment]
Corrected.

By the way, I have found that the Python interface is not adequately 
documented, and the Python examples are not equivalent to the IDL ones 
and require additional data. I will fix that soon.

Alexey
